DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS MESSAGES;

CREATE TABLE USERS (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE MESSAGES (
  ID SERIAL PRIMARY KEY,
  USER_ID INT NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
  MESSAGE TEXT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);